export const dialogues = [
    {
        DialogueNumber: 1,
        CharacterName: "",
        DialogueText: "*Mary sits at her desk, slumped in her seat, anxiously watching the teacher hand back the recent test. The classroom buzzes with students talking as they glance at their grades. Mary catches a glimpse of her score: 43%. Her heart sinks.*",
        BgImage: "../../public/images/intro-assets/Background/schoolDay.png",
        LeftSpriteImage: "",
        RightSpriteImage: "",
        CharacterSettings: "NoSpritesSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 2,
        CharacterName: "Teacher",
        DialogueText: "Mary, we’ll need to talk about this after class. That’s the fourth low score this semester. You’re capable of more.",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Teacher Angry.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 3,
        CharacterName: "Mary",
        DialogueText: "Yeah… I know. I tried studying…?",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Teacher Sad.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Shocked.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "CamShakeEffect",
    },
    {
        DialogueNumber: 4,
        CharacterName: "Sophia",
        DialogueText: "Whoa, that bad? Don’t sweat it, though. It was a hard test.",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Laugh.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 5,
        CharacterName: "Mary",
        DialogueText: "You don’t get it. Mom’s gonna freak. I was so close this time…",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Smile.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sad.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 6,
        CharacterName: "Sophia",
        DialogueText: "Yeah, but, like, a 43? Close to what, exactly?",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Sleepy.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Smug.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 7,
        CharacterName: "Mary",
        DialogueText: "Okay, okay. Just...I can't go through another lecture.",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Normal.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sleepy.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 8,
        CharacterName: "Sophia",
        DialogueText: "Look, maybe she’ll go easy on you this time…? Anyway, are you still coming to Emma’s party tonight?",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Delight.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 9,
        CharacterName: "Mary",
        DialogueText: "I dunno. Probably not. Mom’s already mad about my grades.",
        BgImage: "../../public/images/intro-assets/Background/classroomDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Sophia Normal.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sad.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 10,
        CharacterName: "",
        DialogueText: "*Mary drags herself into the house, tossing her backpack by the door. Her mom is in the kitchen, prepping dinner. She looks up with a smile that quickly fades when she sees Mary’s face.*",
        BgImage: "../../public/images/intro-assets/Background/houseEvening.png",
        LeftSpriteImage: "",
        RightSpriteImage: "",
        CharacterSettings: "NoSpritesSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 11,
        CharacterName: "Mother",
        DialogueText: "Hey, Mary! How was school? How’d you do on that exam?",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Laugh.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 12,
        CharacterName: "Mary",
        DialogueText: "…Not great.",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Delight.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sad.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 13,
        CharacterName: "Mother",
        DialogueText: "Not great? Mary, that’s the fourth bad grade this semester. What’s going on?",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Annoyed.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Annoyed.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "CamShakeEffect",
    },
    {
        DialogueNumber: 14,
        CharacterName: "Mary",
        DialogueText: "I dunno, Mom, it was hard! I studied for it.",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Angry.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sleepy.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 15,
        CharacterName: "Mother",
        DialogueText: "Studied? Mary, if you’d been studying properly, this wouldn’t keep happening. You can’t just slide by with last-minute cramming.",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Annoyed.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 16,
        CharacterName: "Mary",
        DialogueText: "Okay, fine, I get it. Can we please not do this again?",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Normal.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Angry.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 17,
        CharacterName: "Mother",
        DialogueText: "We have to, Mary! I’m not letting you go out tonight, that’s for sure. No party until your grades improve.",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Annoyed.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Normal.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "CamShakeEffect",
    },
    {
        DialogueNumber: 18,
        CharacterName: "Mary",
        DialogueText: "Are you kidding me? I really wanted to go…",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Angry.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Shocked.png",
        CharacterSettings: "RightSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 19,
        CharacterName: "Mother",
        DialogueText: "Then maybe you should’ve put in more effort on that test. You’re staying in. End of discussion.",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "../../public/images/intro-assets/Characters/Mother Normal.png",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Annoyed.png",
        CharacterSettings: "LeftSpriteSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 20,
        CharacterName: "Mary",
        DialogueText: "*turns away, heading to her room* Whatever…",
        BgImage: "../../public/images/intro-assets/Background/kitchenDay.png",
        LeftSpriteImage: "",
        RightSpriteImage: "../../public/images/intro-assets/Characters/Marry Sleepy.png",
        CharacterSettings: "LeftSpriteNotSpeaking",
        VisualFX: "NoFX",
    },
    {
        DialogueNumber: 21,
        CharacterName: "",
        DialogueText: "*Mary slams her bedroom door, flopping onto her bed, staring at the ceiling. She feels trapped and frustrated, her mind buzzing with thoughts. She finally reaches for her laptop, opens it, and begins typing.*",
        BgImage: "../../public/images/intro-assets/Background/room.png",
        LeftSpriteImage: "",
        RightSpriteImage: "",
        CharacterSettings: "NoSpritesSpeaking",
        VisualFX: "NoFX",
    },
];
