version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # App exposed port
      - "5005:5005" # Debugging port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    restart: on-failure
    networks:
      - app_network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
