export interface RawDialogue {
  DialogueNumber: number
  CharacterName: string
  BgImage: string
  LeftSpriteImage: string
  RightSpriteImage: string
  CharacterSettings: 'NoSpritesSpeaking' | 'LeftSpriteSpeaking' | 'RightSpriteSpeaking' | 'LeftSpriteNotSpeaking' | 'RightSpriteNotSpeaking'
  VisualFX: 'NoFX' | 'CamShakeEffect'
}

export const dialogues: RawDialogue[] = [
  {
    DialogueNumber: 1,
    CharacterName: '',
    BgImage: '/images/intro-assets/Background/schoolDay.png',
    LeftSpriteImage: '',
    RightSpriteImage: '',
    CharacterSettings: 'NoSpritesSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 2,
    CharacterName: 'Teacher',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Teacher Angry.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 3,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Teacher Sad.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Shocked.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'CamShakeEffect',
  },
  {
    DialogueNumber: 4,
    CharacterName: 'Sophia',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Laugh.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 5,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Smile.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sad.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 6,
    CharacterName: 'Sophia',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Sleepy.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Smug.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 7,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Normal.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sleepy.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 8,
    CharacterName: 'Sophia',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Delight.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 9,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/classroomDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Sophia Normal.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sad.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 10,
    CharacterName: '',
    BgImage: '/images/intro-assets/Background/houseEvening.png',
    LeftSpriteImage: '',
    RightSpriteImage: '',
    CharacterSettings: 'NoSpritesSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 11,
    CharacterName: 'Mother',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Laugh.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 12,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Delight.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sad.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 13,
    CharacterName: 'Mother',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Annoyed.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Annoyed.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'CamShakeEffect',
  },
  {
    DialogueNumber: 14,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Angry.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sleepy.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 15,
    CharacterName: 'Mother',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Annoyed.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 16,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Normal.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Angry.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 17,
    CharacterName: 'Mother',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Annoyed.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Normal.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'CamShakeEffect',
  },
  {
    DialogueNumber: 18,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Angry.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Shocked.png',
    CharacterSettings: 'RightSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 19,
    CharacterName: 'Mother',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '/images/intro-assets/Characters/Mother Normal.png',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Annoyed.png',
    CharacterSettings: 'LeftSpriteSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 20,
    CharacterName: 'Mary',
    BgImage: '/images/intro-assets/Background/kitchenDay.png',
    LeftSpriteImage: '',
    RightSpriteImage: '/images/intro-assets/Characters/Marry Sleepy.png',
    CharacterSettings: 'LeftSpriteNotSpeaking',
    VisualFX: 'NoFX',
  },
  {
    DialogueNumber: 21,
    CharacterName: '',
    BgImage: '/images/intro-assets/Background/room.png',
    LeftSpriteImage: '',
    RightSpriteImage: '',
    CharacterSettings: 'NoSpritesSpeaking',
    VisualFX: 'NoFX',
  },
]
